### ISSUE TITLE
Moving settings to a separate file

### ISSUE THREAD

**Issue by z411** [incognico/erebus#3]
Hi,

I propose moving the settings to a separate file (settings.pl) that's included by erebus.pl to make working on it through git while keeping the configuration easier. I can submit a PR if you want.

Cheers.

**Comment by incognico** [comment]
I could do that but I would use a yaml or toml config file then.

**Comment by incognico** [comment]
I'm gonna use TOML::Tiny and add support for a command line argument to supply a custom config file, defaulting to config.toml.

Edit: The Tiny modules don't support the regexes, I have to use YAML::XS.

**Comment by incognico** [comment]
Closed via d4291e53f56ba7cd321ca382002915f2c526c4c4

**Comment by z411** [comment]
Thank you! This helps a lot to modify the script and also to run several instances of it for different servers.
